CREATE OR REPLACE FUNCTION add_tick(t timestamp with time zone)
RETURNS integer
AS
$$
BEGIN
RETURN FLOOR((EXTRACT(HOUR FROM t)+2)/2) + (EXTRACT(ISODOW FROM now())-1)*12;
END;
$$
LANGUAGE plpgsql; 

/*carts table */
CREATE TABLE
    carts (
        id int generated always as identity not null PRIMARY KEY,
        customer_name not null text,
        payment_string text,
        created_at timestamp with time zone not null default now(),
        tick integer not null default add_tick(now())     
    );

/*cart items table */
CREATE TABLE
    cart_items (
        id int generated always as identity not null PRIMARY KEY,
        potion_inventory_id int REFERENCES potion_inventory (id),
        quantity int not null default 0, 
        cart_id int REFERENCES carts (id)
   )

/*
potion_inventory table
*/
create table
  public.potion_inventory (
    id bigint generated by default as identity,
    quantity integer not null default 0,
    price integer not null default 0,
    sku text null,
    potion_type integer[] not null default '{}'::integer[],
    name text null,
    max_potion integer not null default 0,
    constraint potion_inventory_pkey primary key (id)
  ) tablespace pg_default;


/*acounts table*/
create table
  public.accounts (
    id bigint generated by default as identity,
    name text null,
    joined_at timestamp with time zone not null default now(),
    constraint accounts_pkey primary key (id),
    constraint accounts_id_key unique (id),
    constraint accounts_name_key unique (name)
  ) tablespace pg_default;


/*transactions table*/
create table
  public.transactions (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    description text null,
    tick integer not null default add_tick(now()),   
    constraint transactions_pkey primary key (id)
  ) tablespace pg_default;


/*ml_ledger*/
create table
  public.ml_ledger (
    id bigint generated by default as identity,
    account_id bigint not null,
    transaction_id bigint not null,
    quantity integer not null,
    type bigint not null,
    constraint ml_ledger_pkey primary key (id),
    constraint ml_ledger_account_id_fkey foreign key (account_id) references accounts (id),
    constraint ml_ledger_transaction_id_fkey foreign key (transaction_id) references transactions (id),
    constraint ml_ledger_type_fkey foreign key (
      type
    ) references ml_type (id)
  ) tablespace pg_default;


/*used for lookup*/
/*potion_table*/
create table
  public.ml_type (
    id bigint generated by default as identity,
    color text not null,
    constraint ml_type_pkey primary key (id),
    constraint ml_type_color_key unique (color)
  ) tablespace pg_default;


/*gold_ledger*/
create table
  public.gold_ledger (
    id bigint generated by default as identity,
    quantity integer not null,
    account_id bigint not null,
    transaction_id bigint not null,
    constraint gold_ledger_pkey primary key (id),
    constraint gold_ledger_account_id_fkey foreign key (account_id) references accounts (id),
    constraint gold_ledger_transaction_id_fkey foreign key (transaction_id) references transactions (id)
  ) tablespace pg_default;

/*potion_ledger*/
create table
  public.potion_ledger (
    id bigint generated by default as identity,
    account_id bigint not null,
    transaction_id bigint not null,
    potion_id bigint not null,
    quantity integer not null,
    constraint potion_ledger_pkey primary key (id),
    constraint potion_ledger_account_id_fkey foreign key (account_id) references accounts (id),
    constraint potion_ledger_potion_id_fkey foreign key (potion_id) references potion_inventory (id),
    constraint potion_ledger_transaction_id_fkey foreign key (transaction_id) references transactions (id)
  ) tablespace pg_default;


/*used for reference*/
/*ticks table (use as a reference for ticks id)
Fields:(prepopulated with 7*12 rows)
dow: int 1-7
time_initial(hour) : int 0-24 
time_end(hour): int 0-24 
ex: if run at 13(1pm) then initial: 12, end: 14
we'll use a csv file to streamline the process... located at tick_table.csv
add id field seperately in supabase...
*/
